// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkjzUoRk5fvyuwj59JTvqBw8jykvlkngo',
    appId: '1:102959828453:web:4ac7468a33f63a631df30c',
    messagingSenderId: '102959828453',
    projectId: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey',
    authDomain: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey.firebaseapp.com',
    storageBucket: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACn1Zz3zwydpUc2FzICnnpQ81XoXRcimw',
    appId: '1:102959828453:android:40a497df6ab4100c1df30c',
    messagingSenderId: '102959828453',
    projectId: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey',
    storageBucket: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF0eGL7HOy7r649dExolBZwmntnM7ik0g',
    appId: '1:102959828453:ios:c4c94aceb2d449bc1df30c',
    messagingSenderId: '102959828453',
    projectId: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey',
    storageBucket: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey.firebasestorage.app',
    iosBundleId: 'com.parellelparadigm.assethtmlcompiler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF0eGL7HOy7r649dExolBZwmntnM7ik0g',
    appId: '1:102959828453:ios:c4c94aceb2d449bc1df30c',
    messagingSenderId: '102959828453',
    projectId: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey',
    storageBucket: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey.firebasestorage.app',
    iosBundleId: 'com.parellelparadigm.assethtmlcompiler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkjzUoRk5fvyuwj59JTvqBw8jykvlkngo',
    appId: '1:102959828453:web:1425ef79b17d05261df30c',
    messagingSenderId: '102959828453',
    projectId: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey',
    authDomain: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey.firebaseapp.com',
    storageBucket: 'tll6lmfmns5lxkwq8q91uu2iz2z1ey.firebasestorage.app',
  );
}
